    Run information
    ---------------
    
    Generates close-on-exception content for `pytenstils.logging`
        functionality.
    
        Start time    : 2024-03-24 17:33:18
    
    --------------------------------------------------------------------------
    
    Unhandled exception
    -------------------
    
*** CRITICAL: The process failed due to an unhandled exception.

    >>> ZeroDivisionError: division by zero
    
        Filename       : T:\Documents\Projects\Pytensils\tests\test_logging.py
        Line Number    : Line 322
        Function       : divide_by_zero()
        Exception      : ZeroDivisionError
    
    --------------------------------------------------------------------------
    
    Run time
    --------
    
    Run-time performance summary.
    
        Start time    : 17:33:18.819100
        End time      : 17:33:19.108891
        Run time      : 00:00:00.289791

    --------------------------------------------------------------------------
